* TODO Написать тест на то, что если падает запущенный таск, можно стартовать новые
То есть ошибка должна попадать в хэндлер

* TODO Задокументировать наличие двух рестартов для аргументов: всего таска и старт-инстанса

* TODO проверить работу с nullable аргументами

* TODO написать тесты на работу с nullable аргументами

* TODO потестить, что работает кейс, когда в start передаётся аргумент равный =null=

* NOTE Почему не стал добавлять queue

Получается там нужно два механизма: один, если юзер хочет стратовать последовательно один и тот же таск с разными аргументами, а второй, если он хочет разные таски друг за другом цеплять.
Можно оставить только второй, но тогда будет глобальная очередь. Или это нормально?
В любом случае, пока не стал делать это, потому что подумал, что руками на основе текущего функционала уже можно забацать свою очередь: слушать окончание одного таска и стартовать другой, поэтому это выглядит как минимум как не самая приоритетная фича библиотеки. Набросок per-task очереди сохранил в файле queue-sketch.diff 
